# hardware
gpu: [ 3 ]
distributed: False
address: '127.0.0.1'
port: '23456'
# model configuration
model: "DRCN"
num_channels: 1
num_recursions: 9
num_filter: 96
# dataset
dataset: "customize"
color_space: 'YCbCr'
img_size: 41
upscaleFactor: [ 2,3,4 ]
test_upscaleFactor: 3
scales: [ 1.0, 0.7, 0.5 ]
rotations: [ 0, 90, 180, 270 ]
flips: [ 0, 1, 2, 3 ]
use_h5py: True
buildRawData: True
platform: linux
force_rebuild: False
seed: 123
#python data_aug.py --number 1 --width 41 --height 41 --stride 21 -uf 2 3 4 \
#				   --rotations 0 90 180 270 --scales 1.0 0.7 0.5 --use_bicubic \
#				   --input /data/lifengjun/data/91-image/HR  --single_y --use_h5py \
#				   --output /data/lifengjun/data/super_resolution/data_for_DRCN/test.h5
data_flist:
  windows:
    origin_HR_dir: "F:\\cache\\data\\291-image\\HR"
    train_HR_dir: "F:\\cache\\data\\291-image\\HR_train"
    train_LR_dir: "F:\\cache\\data\\291-image\\LR_train"
    test_HR_dir: "F:\\cache\\data\\Set5,Set14\\set5_HR\\3"
    test_LR_dir: "F:\\cache\\data\\Set5,Set14\\set5_LR\\3"
  linux:
    origin_HR_dir: "/data/data/291-images"
    train_HR_dir: "/data/data/super_resolution/data_for_DRCN/HR_train"
    train_LR_dir: "/data/data/super_resolution/data_for_DRCN/LR_train"
    test_HR_dir: "/data/lifengjun/data/Set5/HR_x2/"
    test_LR_dir: "/data/lifengjun/data/Set5/LR_x2/"
    h5py_input: "/data/lifengjun/data/super_resolution/data_for_DRCN/test.h5"
# experiment
lr: 0.01
training_batch_size: 64
test_batch_size: 1
clip: 0.01
loss_alpha: 1.0
loss_beta: 0.0001
loss_alpha_zero_epoch: 25
momentum: 0.9
weight_decay: 0.0001
scheduler_gamma: 0.1
scheduler_patience: 5
scheduler_factor: 0.1
scheduler_min_lr: 0.000001
scheduler_threshold: 0.0001
epochs: 100
milestones: [ 50, 70, 80, 90 ]
# checkpoint
checkpoint_interval: 1
checkpoint_dir: "checkpoints/"
# visualization
tensorboard_log_dir: "runs/drcn"
tensorboard_image_interval: 1
tensorboard_image_sample: 10
tensorboard_image_size: [ 256, 256 ]
tensorboard_draw_model: True
tensorboard_input: [ 64, 1, 41, 41 ]
