# hardware
gpu: [ 0, 1 ]
distributed: True
address: '127.0.0.1'
port: '23456'
# models configuration
model: "EDSR"
n_colors: 3
n_feats: 64         # 256 for paper
n_resblocks: 16     # 32 for paper
res_scale: 1        # 0.1 for paper
# dataset
dataset: "customize"
color_space: 'RGB'
rgb_range: 255
img_size: 48  # size of LR is 48
upscaleFactor: [ 2 ]
test_upscaleFactor: 2
scales: [ 1.0 ]
rotations: [ 0, 90 ]
flips: [ 0, 1, 2 ]
use_h5py: True
buildAugData: False
platform: linux
seed: 123
data_flist:
  windows:
    origin_HR_dir: "F:\\cache\\data\\291-image\\HR"
    train_HR_dir: "F:\\cache\\data\\291-image\\HR_train"
    train_LR_dir: "F:\\cache\\data\\291-image\\LR_train"
    test_HR_dir: "F:\\cache\\data\\Set5,Set14\\set5_HR\\2"
    test_LR_dir: "F:\\cache\\data\\Set5,Set14\\set5_LR\\2"
  linux:
    origin_HR_dir: "/data/data/291-images"
    train_HR_dir: "/data/data/DIV2K/DIV2K/DIV2K_train_LR_bicubic/X2"
    train_LR_dir: "/data/data/DIV2K/DIV2K/DIV2K_train_HR"
    test_HR_dir: "/data/data/Set5,Set14/set5_HR/2/"
    test_LR_dir: "/data/data/Set5,Set14/set5_LR/2/"
    h5py_input: "/data/data/super_resolution/data_for_RDN/train.h5"
# experiment
lr: 0.0001
eps: 1e-8
beta1: 0.9
beta2: 0.999
batch_size: 16
epochs: 100
milestones: [ 50, 70, 80, 90 ]
# checkpoint
checkpoint_interval: 1
checkpoint_dir: "checkpoints/"
# visualization
tensorboard_log_dir: "runs/vdsr"
tensorboard_image_interval: 1
tensorboard_image_sample: 10
tensorboard_image_size: [ 256, 256 ]
tensorboard_draw_model: True
tensorboard_input: [ 64, 1, 41, 41 ]
