# hardware
gpu: [ 1 ]
distributed: False
address: '127.0.0.1'
port: '23456'
# models configuration
model: "ESPCN"
img_channels: 1
num_filter: 64
# dataset
dataset: "customize"
color_space: 'YCbCr'
img_size: 17
upscaleFactor: [ 2 ]
test_upscaleFactor: 2
scales: [ 1.0 ]
rotations: [ 0 ]
flips: [ 0 ]
use_h5py: True
buildAugData: True
platform: linux
seed: 123
data_flist:
  windows:
    origin_HR_dir: "F:\\cache\\data\\291-image\\HR"
    train_HR_dir: "F:\\cache\\data\\291-image\\HR_train"
    train_LR_dir: "F:\\cache\\data\\291-image\\LR_train"
    test_HR_dir: "F:\\cache\\data\\Set5,Set14\\set5_HR\\3"
    test_LR_dir: "F:\\cache\\data\\Set5,Set14\\set5_LR\\3"
  linux:
    origin_HR_dir: "/data/data/291-images"
    train_HR_dir: "/data/data/super_resolution/data_for_ESPCN/HR_train"
    train_LR_dir: "/data/data/super_resolution/data_for_ESPCN/LR_train"
    test_HR_dir: "/data/data/Set5/HR/"
    test_LR_dir: "/data/data/Set5/LR_bicubic/X2/"
    h5py_input: "/data/data/super_resolution/data_for_ESPCN/train_x2.h5"
# experiment
lr: 0.001
batch_size: 64
scheduler_gamma: 0.1
scheduler_patience: 10
scheduler_factor: 0.1
scheduler_min_lr: 0.0001
scheduler_threshold: 0.00001
epochs: 3000
milestones: [ 100, 500, 1000 ]
# checkpoint
checkpoint_interval: 1
checkpoint_dir: "checkpoints/"
# visualization
tensorboard_log_dir: "runs/espcn"
tensorboard_image_interval: 1
tensorboard_image_sample: 10
tensorboard_image_size: [ 256, 256 ]
tensorboard_draw_model: True
tensorboard_input: [ 64, 1, 17, 17 ]
