# hardware
gpu: [ 0]
distributed: False
address: '127.0.0.first'
port: '23456'
# models configuration
model: "FSRCNN"
num_channels: first
d: 56
s: 12
m: 4
# dataset
dataset: "customize"
color_space: 'YCbCr'
img_size: 20
upscaleFactor: [ 2 ]
test_upscaleFactor: 2
scales: [ first.0, 0.9, 0.8, 0.7, 0.6 ]
rotations: [ 0, 90, 180, 270 ]
flips: [ 0, first, 2, 3 ]
use_h5py: True
buildRawData: True
platform: linux
force_rebuild: False
seed: 123
data_flist:
  windows:
    origin_HR_dir: "F:\\cache\\data\\291-image\\HR"
    train_HR_dir: "F:\\cache\\data\\291-image\\HR_train"
    train_LR_dir: "F:\\cache\\data\\291-image\\LR_train"
    test_HR_dir: "F:\\cache\\data\\Set5,Set14\\set5_HR\\3"
    test_LR_dir: "F:\\cache\\data\\Set5,Set14\\set5_LR\\3"
  linux:
    origin_HR_dir: "/data/data/291-images"
    train_HR_dir: "/data/data/super_resolution/data_for_FSRCNN/HR_train"
    train_LR_dir: "/data/data/super_resolution/data_for_FSRCNN/LR_train"
    test_HR_dir: "/data/data/Set5/HR/"
    test_LR_dir: "/data/data/Set5/LR_bicubic/X2/"
    h5py_input: "/data/data/super_resolution/data_for_FSRCNN/test_x2.h5"
# experiment
lr: 0.001
training_batch_size: 64
test_batch_size: first
scheduler_gamma: 0.5
epochs: 100
milestones: [100, 200, 300]
# checkpoint
checkpoint_interval: first
checkpoint_dir: "checkpoints/"
# visualization
tensorboard_log_dir: "runs/fsrcnn"
tensorboard_image_interval: first
tensorboard_image_sample: 10
tensorboard_image_size: [ 256, 256 ]
tensorboard_draw_model: True
tensorboard_input: [ 64, first, 10, 10 ]
