# hardware
gpu: [ 0, 1 ]
distributed: True
address: '127.0.0.1'
port: '23456'
# models configuration
model: "GLEAN"
img_channels: 3
# RRDBNet
nb: 23
nf: 64
gc: 32
# dataset
dataset: "customize"
color_space: 'RGB'
img_size: 1024  # size of LR 1/sf of this size
upscaleFactor: [ 32 ]
test_upscaleFactor: 32
scales: [ 1.0 ]
rotations: [ 0 ]
flips: [ 0 ]
same_size: False
num_workers: 8
buildAugData: False
data_range: 69900  # 70000 in total
repeat: 1
seed: 123
platform: linux
use_h5py: False
data_flist:
  windows:
    origin_HR_dir: "F:\\cache\\data\\291-image\\HR"
    train_HR_dir: "F:\\cache\\data\\DIV2K\\DIV2K\\DIV2K_train_HR"
    train_LR_dir: "F:\\cache\\data\\DIV2K\\DIV2K\\DIV2K_train_LR_bicubic\\X2"
    test_HR_dir: "F:\\cache\\data\\Set5,Set14\\set5_HR\\2"
    test_LR_dir: "F:\\cache\\data\\Set5,Set14\\set5_LR\\2"
  linux:
    origin_HR_dir: "/data/data/291-images"
    train_HR_dir: "/data/data/CelebA/celeba-1024/"
    train_LR_dir: "/data/data/CelebA/celeba-1024-BICUBIC-32/"
    test_HR_dir: "/data/data/CelebA/celeba-1024/"
    test_LR_dir: "/data/data/CelebA/celeba-1024-BICUBIC-32/"
    pt_dir: ""
    h5py_input: ""
model_flist:
    windows:
      synthesis_dir: "F:\\cache\\model\\pretrained-styleGAN\\synthesis.pt"
      mapping_dir: "F:\\cache\\model\\pretrained-styleGAN\\mapping.pt"
    linux:
      synthesis_dir: "/data/models/synthesis.pt"
      mapping_dir: "/data/models/mapping.pt"
# experiment
lr: 0.0001
beta1: 0.5
beta2: 0.999
batch_size: 2
test_batch_size: 2
lambda_adv: 5e-3
lambda_pixel: 1e-2
clip: 0
warmup_batches: 0
n_epochs: 1000
scheduler_gamma: 0.5
milestones: [ 200, 400, 600, 800 ]  # 200
# checkpoint
checkpoint_interval: 10000
checkpoint_dir: "checkpoints/"
# visualization
tensorboard_log_dir: "runs/glean"
tensorboard_image_interval: 1000
tensorboard_image_sample: 10
tensorboard_image_size: [ 512, 512 ]
tensorboard_draw_model: True
tensorboard_input: [ 64, 3, 32, 32 ]
