# hardware
gpu: [ 0 ]
distributed: False
address: '127.0.0.1'
port: '23456'
# models configuration
model: "RDN"
img_channels: 3
num_features: 64
growth_rate: 64
num_blocks: 16
num_layers: 8
# dataset
dataset: "customize"
color_space: 'RGB'
img_size: 144  # size of LR 1/sf of this size
upscaleFactor: [ 3 ]
test_upscaleFactor: 3
scales: [ 1.0 ]
rotations: [ 0, 90 ]
flips: [ 0, 1, 2 ]
same_size: False
num_workers: 8
buildAugData: False
data_range: 800
repeat: 20
seed: 123
platform: linux
use_h5py: False
data_flist:
  windows:
    origin_HR_dir: "F:\\cache\\data\\291-image\\HR"
    train_HR_dir: "F:\\cache\\data\\DIV2K\\DIV2K\\DIV2K_train_HR"
    train_LR_dir: "F:\\cache\\data\\DIV2K\\DIV2K\\DIV2K_train_LR_bicubic\\X2"
    test_HR_dir: "F:\\cache\\data\\Set5,Set14\\set5_HR\\2"
    test_LR_dir: "F:\\cache\\data\\Set5,Set14\\set5_LR\\2"
  linux:
    origin_HR_dir: "/data/data/291-images"
    train_HR_dir: "/data/data/DIV2K/DIV2K/DIV2K_train_HR"
    train_LR_dir: "/data/data/DIV2K/DIV2K/DIV2K_train_LR_bicubic/X3"
    test_HR_dir: "/data/data/Set5,Set14/set5_HR/3/"
    test_LR_dir: "/data/data/Set5,Set14/set5_LR/3/"
    pt_dir: ""
    h5py_input: ""
# experiment
lr: 0.0001
batch_size: 16
clip: 0
epochs: 1000
scheduler_gamma: 0.5
milestones: [ 200, 400, 600, 800 ]  # 200
# checkpoint
checkpoint_interval: 1
checkpoint_dir: "checkpoints/"
# visualization
tensorboard_log_dir: "runs/rdn"
tensorboard_image_interval: 1
tensorboard_image_sample: 10
tensorboard_image_size: [ 256, 256 ]
tensorboard_draw_model: True
tensorboard_input: [ 64, 3, 32, 32 ]
