# hardware
gpu: [0]
distributed: False
address: '127.0.0.1'
port: '23456'
# models
model: "SRCNN"
num_filter: 64
img_channels: 1
# dataset
dataset: "customize"
color_space: 'YCbCr'
img_size: 33
upscaleFactor: [3]
test_upscaleFactor: 3
scales: [1.0]
rotations: [0]
flips: [0]
use_h5py: True
buildAugData: True
platform: windows
seed: 123
data_flist:
  windows:
    origin_HR_dir: "F:\\cache\\data\\291-image\\HR"
    train_HR_dir: "F:\\cache\\data\\291-image\\HR_train"
    train_LR_dir: "F:\\cache\\data\\291-image\\LR_train"
    test_HR_dir: "F:\\cache\\data\\Set5_SR\\HR_2"
    test_LR_dir: "F:\\cache\\data\\Set5_SR\\LR_2"
    h5py_input: "F:\\cache\\data\\data_for_SRCNN\\train_x2.h5"
  linux:
    origin_HR_dir: "/data/data/291-images"
    train_HR_dir: "/data/data/super_resolution/data_for_VDSR/HR_train"
    train_LR_dir: "/data/data/super_resolution/data_for_VDSR/LR_train"
    test_HR_dir: "/data/data/Set5/HR_x2/"
    test_LR_dir: "/data/data/Set5/LR_x2/"
    h5py_input: "/data/data/super_resolution/data_for_VDSR/train.h5"
# experiments
lr: 0.1
batch_size: 32
momentum: 0.9
weight_decay: 0.0001
scheduler_gamma: 0.95
epochs: 2000
milestones: [1000, 1250, 1500, 2000]
# checkpoint
checkpoint_interval: 1
checkpoint_dir: "checkpoints/"
# visualization
tensorboard_log_dir: "runs/srcnn"
tensorboard_image_interval: 1
tensorboard_image_sample: 10
tensorboard_image_size: [ 256, 256 ]
tensorboard_draw_model: True
tensorboard_input: [ 64, 1, 33, 33 ]
