model: "SRCNN"
filter: 64
dataset: "91-images"
num_channels: 1
color_space: 'YCrCb'
upscaleFactor: 4
lr: 0.01
training_batch_size: 16
test_batch_size: 1
img_size: 33
momentum: 0.9
weight_decay: 0.0
scheduler_gamma: 0.95
gpus: 1
epochs: 20000
