# hardware
gpu: [ 1 ]
distributed: False
address: '127.0.0.1'
port: '23456'
# model configuration
model: "VDSR"
num_channels: 1
num_residuals: 20
num_filter: 64
# dataset
dataset: "customize"
color_space: 'YCbCr'
img_size: 41
upscaleFactor: [ 2,3,4 ]
test_upscaleFactor: 3
scales: [ 1.0, 0.7, 0.5 ]
rotations: [ 0, 90, 180, 270 ]
flips: [ 0, 1, 2, 3 ]
use_h5py: True

buildRawData: True
platform: linux
force_rebuild: False
data_flist:
  windows:
    origin_HR_dir: "F:\\cache\\data\\291-image\\HR"
    train_HR_dir: "F:\\cache\\data\\291-image\\HR_train"
    train_LR_dir: "F:\\cache\\data\\291-image\\LR_train"
    test_HR_dir: "F:\\cache\\data\\Set5,Set14\\set5_HR\\3"
    test_LR_dir: "F:\\cache\\data\\Set5,Set14\\set5_LR\\3"
  linux:
    origin_HR_dir: "/data/data/291-image/HR"
    train_HR_dir: "/data/data/291-image/HR_train"
    train_LR_dir: "/data/data/291-image/LR_train"
    test_HR_dir: "/data/data/Set5,Set14/set5_HR/2/"
    test_LR_dir: "/data/data/Set5,Set14/set5_LR/2/"
    h5py_input: "/data/data/super_resolution/data_for_VDSR/train.h5"
# experiment
lr: 0.01
training_batch_size: 256
test_batch_size: 1
clip: 0.4
momentum: 0.9
weight_decay: 0.0001
scheduler_gamma: 0.1
epochs: 100
milestones: [ 10, 20, 30, 50 ]
# checkpoint
checkpoint_interval: 1
checkpoint_dir: "checkpoints/"
# visualization
tensorboard_log_dir: "runs/"
tensorboard_image_interval: 1
tensorboard_image_sample: 10
tensorboard_image_size: [ 256, 256 ]
tensorboard_draw_model: True
tensorboard_input: [ 64, 1, 41, 41 ]
