# hardware
gpu: [ 0 ]
distributed: False
address: '127.0.0.1'
port: '23456'
# models configuration
model: "wgan"
latent_dim: 100
# dataset
dataset: "mnist"
channels: 1
img_size: 32
n_classes: 10
seed: 123
num_workers: 8
platform: windows
data_flist:
  windows:
    train_dir: F:\\cache\\data
    test_dir: F:\\cache\\data
  linux:
    train_dir: /data/data/lifengjun/mnist
    test_dir: /data/data/lifengjun/mnist
# experiment
epochs: 200
batch_size: 64
lr: 0.0002
beta1: 0.5
beta2: 0.999
clip_value: 0.01  # lower and upper clip value for disc. weights
n_critic: 5       # number of training steps for discriminator per iter
# checkpoint
sample_interval: 400